modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "discord_auth_for_mc"
version = "${version}"
displayName = "Discord Auth for MC"
authors = "Me!"
description = '''
A Minecraft mod that allows players to use their Discord accounts for authentication on multiplayer servers instead of official Minecraft accounts
'''
#logoFile = ""

[[dependencies.discord_auth_for_mc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discord_auth_for_mc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.discord_auth_for_mc]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "discord_auth_for_mc.mixins.json"
